# Generated by Django 4.1.3 on 2022-11-29 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Fields', '0002_field_poly_coord1_field_poly_coord2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='poly_coord4',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
